import subprocess
import re
from github import Github
import os

def slugify(text: str) -> str:
    """Turns a task description into a safe branch-name fragment."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:50]

def open_pr(repo_name: str, branch_name: str, title: str, body: str, base: str = "main") -> str:
    """Uses PyGithub to open the PR on the remote repository."""
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN is missing. Please export it in your terminal.")
        
    gh = Github(token)
    repo = gh.get_repo(repo_name)
    pr = repo.create_pull(title=title, body=body, head=branch_name, base=base)
    return pr.html_url

def ship_change(repo_path: str, changed_files: list[str], task_description: str,
                 repo_name: str, base: str = "main") -> str:
    """Runs the actual git mechanics, then opens the PR."""
    
    branch_name = f"locdex/{slugify(task_description)}"

    print(f"[git] Creating branch: {branch_name}")
    subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_path, check=True)

    print(f"[git] Staging {len(changed_files)} files...")
    # Only stage the specific files Locdex touched, not a blanket `git add .`
    if changed_files:
        subprocess.run(["git", "add"] + changed_files, cwd=repo_path, check=True)

    print("[git] Committing changes...")
    subprocess.run(["git", "commit", "-m", task_description], cwd=repo_path, check=True)

    print("[git] Pushing to remote...")
    subprocess.run(["git", "push", "-u", "origin", branch_name], cwd=repo_path, check=True)

    print("[git] Opening Pull Request...")
    return open_pr(repo_name, branch_name, title=task_description,
                    body=f"Generated by Locdex.\n\nTask: {task_description}", base=base)