import os
import subprocess
import uuid
import re
from github import Github

def get_github_repo_name(repo_path: str = ".") -> str:
    """
    Dynamically extracts the 'owner/repo' string from the local git remote origin.
    Handles both HTTPS and SSH URLs.
    """
    try:
        result = subprocess.run(
            ["git", "config", "--get", "remote.origin.url"],
            cwd=repo_path,
            capture_output=True,
            text=True,
            check=True
        )
        url = result.stdout.strip()
        
        match = re.search(r'(?:github\.com[:/])([^/]+/[^/\.]+)', url)
        if match:
            repo_str = match.group(1)
            if repo_str.endswith('.git'):
                repo_str = repo_str[:-4]
            return repo_str
        else:
            raise ValueError(f"Could not parse GitHub repo name from origin URL: {url}")
            
    except subprocess.CalledProcessError:
        raise RuntimeError("Failed to get remote.origin.url. Is this a Git repository with an origin configured?")

def ship_change(repo_path: str, changed_files: list, task_description: str, repo_name: str = None) -> str:
    """
    Automates branching, committing, pushing, and creating a Pull Request on GitHub.
    Dynamically detects the repository if repo_name is not provided.
    """
    if not repo_name:
        repo_name = get_github_repo_name(repo_path)

    github_token = os.environ.get("GITHUB_TOKEN")
    if not github_token:
        raise ValueError("GITHUB_TOKEN environment variable is missing. Cannot create PR.")

    safe_name = re.sub(r'[^a-zA-Z0-9-]', '-', task_description[:40].lower()).strip('-')
    branch_name = f"locdex/{safe_name}-{str(uuid.uuid4())[:6]}"

    subprocess.run(["git", "checkout", "-b", branch_name], cwd=repo_path, check=True)
    
    # SECURITY FIX: Added '--' so changed_files are strictly treated as paths, not flags
    subprocess.run(["git", "add", "--"] + changed_files, cwd=repo_path, check=True)
    
    commit_msg = f"{task_description}\n\nGenerated by Locdex AI Agent."
    subprocess.run(["git", "commit", "-m", commit_msg], cwd=repo_path, check=True)
    subprocess.run(["git", "push", "-u", "origin", branch_name], cwd=repo_path, check=True)

    g = Github(github_token)
    repo = g.get_repo(repo_name)
    
    pr = repo.create_pull(
        title=f"Locdex: {task_description[:50]}",
        body=f"Autogenerated PR by Locdex agent.\n\n**Task:** {task_description}",
        head=branch_name,
        base="main"
    )
    
    subprocess.run(["git", "checkout", "main"], cwd=repo_path, check=True)
    
    return pr.html_url